// <auto-generated />
using System;
using Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260106132234_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("ProductId");

                    b.HasIndex("Slug");

                    b.ToTable("inventories", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.Models.Inventory", b =>
                {
                    b.OwnsMany("Inventory.Domain.Models.InventoryColorVariant", "ColorVariants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("color");

                            b1.Property<Guid>("ColorVariantId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("color_variant_id");

                            b1.Property<Guid>("inventory_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ColorVariantId");

                            b1.HasIndex("inventory_id");

                            b1.ToTable("inventory_color_variants", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("inventory_id");

                            b1.OwnsMany("Inventory.Domain.Models.InventorySizeVariant", "SizeVariants", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("id");

                                    b2.Property<int>("Reserved")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasDefaultValue(0)
                                        .HasColumnName("reserved");

                                    b2.Property<string>("Size")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("size");

                                    b2.Property<Guid>("color_variant_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("Size");

                                    b2.HasIndex("color_variant_id");

                                    b2.ToTable("inventory_size_variants", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("color_variant_id");

                                    b2.OwnsOne("Shared.Domain.ValueObjects.Stock", "Stock", b3 =>
                                        {
                                            b3.Property<Guid>("InventorySizeVariantId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("High")
                                                .HasColumnType("int")
                                                .HasColumnName("high_threshold");

                                            b3.Property<int>("Low")
                                                .HasColumnType("int")
                                                .HasColumnName("low_threshold");

                                            b3.Property<int>("Mid")
                                                .HasColumnType("int")
                                                .HasColumnName("mid_threshold");

                                            b3.Property<int>("Value")
                                                .HasColumnType("int")
                                                .HasColumnName("stock_value");

                                            b3.HasKey("InventorySizeVariantId");

                                            b3.ToTable("inventory_size_variants", "inventory");

                                            b3.WithOwner()
                                                .HasForeignKey("InventorySizeVariantId");
                                        });

                                    b2.OwnsMany("Shared.Domain.ValueObjects.Warehouse", "Warehouses", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uniqueidentifier")
                                                .HasColumnName("id");

                                            b3.Property<string>("Address")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("nvarchar(500)")
                                                .HasColumnName("address");

                                            b3.Property<string>("City")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)")
                                                .HasColumnName("city");

                                            b3.Property<string>("Code")
                                                .IsRequired()
                                                .HasMaxLength(50)
                                                .HasColumnType("nvarchar(50)")
                                                .HasColumnName("code");

                                            b3.Property<string>("ContactEmail")
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)")
                                                .HasColumnName("contact_email");

                                            b3.Property<string>("ContactPhone")
                                                .HasMaxLength(50)
                                                .HasColumnType("nvarchar(50)")
                                                .HasColumnName("contact_phone");

                                            b3.Property<string>("Country")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)")
                                                .HasColumnName("country");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)")
                                                .HasColumnName("name");

                                            b3.Property<string>("PostalCode")
                                                .HasMaxLength(20)
                                                .HasColumnType("nvarchar(20)")
                                                .HasColumnName("postal_code");

                                            b3.Property<string>("State")
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)")
                                                .HasColumnName("state");

                                            b3.Property<Guid>("size_variant_id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.HasKey("Id");

                                            b3.HasIndex("Code");

                                            b3.HasIndex("size_variant_id");

                                            b3.ToTable("inventory_warehouse_locations", "inventory");

                                            b3.WithOwner()
                                                .HasForeignKey("size_variant_id");
                                        });

                                    b2.Navigation("Stock")
                                        .IsRequired();

                                    b2.Navigation("Warehouses");
                                });

                            b1.Navigation("SizeVariants");
                        });

                    b.Navigation("ColorVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
