// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Persistence;

#nullable disable

namespace Product.Persistence.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20251227164100_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float")
                        .HasColumnName("average_rating");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_Deleted");

                    b.Property<decimal?>("NewPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_price");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_product_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<int>("TotalSales")
                        .HasColumnType("int")
                        .HasColumnName("total_sold_items");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AverageRating");

                    b.HasIndex("Brand");

                    b.HasIndex("Discount");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("Price");

                    b.HasIndex("TotalReviews");

                    b.HasIndex("TotalSales");

                    b.ToTable("Products", "products");
                });

            modelBuilder.Entity("Product.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("review_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("float(3)")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews", "products");
                });

            modelBuilder.Entity("Product.Domain.Models.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("color");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sku");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Color");

                    b.HasIndex("ProductId");

                    b.HasIndex("Size");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("ProductId", "Color", "Size");

                    b.ToTable("Variants", "products");
                });

            modelBuilder.Entity("Product.Domain.Models.Product", b =>
                {
                    b.HasOne("Product.Domain.Models.Product", "ParentProduct")
                        .WithMany("Alternatives")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsMany("Shared.Domain.ValueObjects.Image", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("alt_text");

                            b1.Property<bool>("IsMain")
                                .HasColumnType("bit")
                                .HasColumnName("is_main");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("images", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.ImageUrl", "ImageUrl", b2 =>
                                {
                                    b2.Property<Guid>("ImageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("PublicId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("image_publicId");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("image_url");

                                    b2.HasKey("ImageId");

                                    b2.ToTable("images", "products");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageId");
                                });

                            b1.Navigation("ImageUrl")
                                .IsRequired();
                        });

                    b.OwnsOne("Product.Domain.ValueObjects.Category", "Category", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Main")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("category_main");

                            b1.Property<string>("Sub")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("category_sub");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Main");

                            b1.HasIndex("Sub");

                            b1.ToTable("Products", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Product.Domain.ValueObjects.ProductType", "ProductType", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SubType")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("product_subtype");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("product_type");

                            b1.HasKey("ProductId");

                            b1.HasIndex("SubType");

                            b1.HasIndex("Type");

                            b1.ToTable("Products", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Product.Domain.ValueObjects.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsBestSeller")
                                .HasColumnType("bit")
                                .HasColumnName("is_best_seller");

                            b1.Property<bool>("IsFeatured")
                                .HasColumnType("bit")
                                .HasColumnName("is_featured");

                            b1.Property<bool>("IsNew")
                                .HasColumnType("bit")
                                .HasColumnName("is_new");

                            b1.Property<bool>("IsTrending")
                                .HasColumnType("bit")
                                .HasColumnName("is_trending");

                            b1.HasKey("ProductId");

                            b1.HasIndex("IsBestSeller");

                            b1.HasIndex("IsFeatured");

                            b1.HasIndex("IsNew");

                            b1.HasIndex("IsTrending");

                            b1.ToTable("Products", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Shared.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("slug");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value");

                            b1.ToTable("Products", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("Product.Domain.Models.MaterialDetail", "MaterialDetails", b1 =>
                        {
                            b1.Property<Guid>("product_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Detail")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("detail");

                            b1.Property<decimal>("Percentage")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("percentage");

                            b1.HasKey("product_id", "Detail");

                            b1.HasIndex("product_id");

                            b1.ToTable("product_material_details", "products");

                            b1.WithOwner()
                                .HasForeignKey("product_id");

                            b1.OwnsOne("Product.Domain.ValueObjects.Material", "Material", b2 =>
                                {
                                    b2.Property<Guid>("MaterialDetailproduct_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("MaterialDetailDetail")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)")
                                        .HasColumnName("material");

                                    b2.HasKey("MaterialDetailproduct_id", "MaterialDetailDetail");

                                    b2.HasIndex("Name")
                                        .HasDatabaseName("IX_ProductMaterialDetails_Material");

                                    b2.ToTable("product_material_details", "products");

                                    b2.WithOwner()
                                        .HasForeignKey("MaterialDetailproduct_id", "MaterialDetailDetail");
                                });

                            b1.Navigation("Material")
                                .IsRequired();
                        });

                    b.OwnsMany("Product.Domain.ValueObjects.Attribute", "DetailsAttributes", b1 =>
                        {
                            b1.Property<Guid>("product_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("attribute_name");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("attribute_description");

                            b1.HasKey("product_id", "Name");

                            b1.ToTable("product_details_attributes", "products");

                            b1.WithOwner()
                                .HasForeignKey("product_id");
                        });

                    b.OwnsMany("Product.Domain.ValueObjects.Attribute", "SizeFitAttributes", b1 =>
                        {
                            b1.Property<Guid>("product_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("attribute_name");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("attribute_description");

                            b1.HasKey("product_id", "Name");

                            b1.ToTable("product_sizefit_attributes", "products");

                            b1.WithOwner()
                                .HasForeignKey("product_id");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("DetailsAttributes");

                    b.Navigation("Images");

                    b.Navigation("MaterialDetails");

                    b.Navigation("ParentProduct");

                    b.Navigation("ProductType")
                        .IsRequired();

                    b.Navigation("SizeFitAttributes");

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Product.Domain.Models.Review", b =>
                {
                    b.HasOne("Product.Domain.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Product.Domain.ValueObjects.Comment", "Comment", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("comment");

                            b1.HasKey("ReviewId");

                            b1.ToTable("reviews", "products");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("Comment")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Product.Domain.Models.Variant", b =>
                {
                    b.HasOne("Product.Domain.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Shared.Domain.ValueObjects.Image", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("alt_text");

                            b1.Property<bool>("IsMain")
                                .HasColumnType("bit")
                                .HasColumnName("is_main");

                            b1.Property<Guid>("VariantId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VariantId");

                            b1.ToTable("VariantImages", "products");

                            b1.WithOwner()
                                .HasForeignKey("VariantId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.ImageUrl", "ImageUrl", b2 =>
                                {
                                    b2.Property<Guid>("ImageId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("PublicId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("image_publicId");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("image_url");

                                    b2.HasKey("ImageId");

                                    b2.ToTable("VariantImages", "products");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageId");
                                });

                            b1.Navigation("ImageUrl")
                                .IsRequired();
                        });

                    b.Navigation("Images");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Product.Domain.Models.Product", b =>
                {
                    b.Navigation("Alternatives");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
