// <auto-generated />
using System;
using Basket.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.Persistence.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20260113202918_add_Index_CouponStatusx")]
    partial class add_Index_CouponStatusx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("basket")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basket.Domain.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_out");

                    b.Property<decimal>("ShipmentCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipment_cost");

                    b.Property<decimal>("Tax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("TotalSub")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_sub");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("carts", "basket");
                });

            modelBuilder.Entity("Basket.Domain.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("CouponStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MinimumPurchaseAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("minimum_purchase_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasFilter("[CartId] IS NOT NULL");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CouponStatus");

                    b.HasIndex("UserId");

                    b.ToTable("coupons", "basket");
                });

            modelBuilder.Entity("Basket.Domain.Models.Cart", b =>
                {
                    b.OwnsOne("Basket.Domain.ValueObjects.Discount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DiscountType")
                                .HasColumnType("int")
                                .HasColumnName("discount_type");

                            b1.Property<decimal>("DiscountValue")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("discount_value");

                            b1.HasKey("CartId");

                            b1.ToTable("carts", "basket");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.OwnsOne("Shared.Domain.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("delivery_address_city");

                            b1.Property<string>("ExtraDetails")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("delivery_address_extra_details");

                            b1.Property<long>("HouseNumber")
                                .HasColumnType("bigint")
                                .HasColumnName("delivery_address_house_number");

                            b1.Property<long>("PostalCode")
                                .HasColumnType("bigint")
                                .HasColumnName("delivery_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("delivery_address_street");

                            b1.HasKey("CartId");

                            b1.ToTable("carts", "basket");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.OwnsMany("Basket.Domain.Models.LineItem", "LineItems", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("cart_id");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("product_id");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("ColorVariantId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("variant_id");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("image_url");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SizeVariantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("slug");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("cart_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CartId", "ProductId");

                            b1.HasIndex("CartId");

                            b1.HasIndex("ProductId");

                            b1.HasIndex("cart_id");

                            b1.ToTable("line_items", "basket", t =>
                                {
                                    t.Property("cart_id")
                                        .HasColumnName("cart_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("cart_id");
                        });

                    b.OwnsMany("Shared.Domain.ValueObjects.CouponId", "CouponIds", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("coupon_id");

                            b1.Property<Guid>("cart_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("id");

                            b1.HasIndex("cart_id");

                            b1.ToTable("coupon_ids", "basket");

                            b1.WithOwner()
                                .HasForeignKey("cart_id");
                        });

                    b.Navigation("CouponIds");

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Basket.Domain.Models.Coupon", b =>
                {
                    b.OwnsOne("Basket.Domain.ValueObjects.Discount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DiscountType")
                                .HasColumnType("int")
                                .HasColumnName("discount_type");

                            b1.Property<decimal>("DiscountValue")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("discount_value");

                            b1.HasKey("CouponId");

                            b1.ToTable("coupons", "basket");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.Navigation("Discount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
