using System.Reflection;

using Inventory;

using MassTransit;

using Microsoft.OpenApi.Models;

using Payment;

using Shared;
using Shared.Application.Extensions;

using Shipment;

namespace Api;

internal class Program
{
    public static void Main(string[] args)
    {

        var builder = WebApplication.CreateBuilder(args);

        if (builder.Environment.IsDevelopment())
            builder.Configuration.AddUserSecrets<Program>();



        builder.Host.UseSerilog((ctx, config) =>
        {
            config.ReadFrom.Configuration(ctx.Configuration);
        });



        builder.Configuration.AddEnvironmentVariables();
        var productAssembly = typeof(ProductModule).Assembly;
        var basketAssembly = typeof(CartModule).Assembly;
        var orderAssembly = typeof(OrderModule).Assembly;
        var identityAssembly = typeof(IdentityModule).Assembly;
        var paymentAssembly = typeof(PaymentModule).Assembly;
        var shipmentAssembly = typeof(ShipmentModule).Assembly;
        var inventoryAssembly = typeof(InventoryModule).Assembly;

        builder.Services.AddSharedModule(builder.Configuration);
        builder.Services.AddIdentityModule(builder.Configuration);
        builder.Services.AddProductModule(builder.Configuration);
        builder.Services.AddBasketModule(builder.Configuration);
        builder.Services.AddOrderModule(builder.Configuration);
        builder.Services.AddShipmentModule(builder.Configuration);
        builder.Services.AddPaymentModule(builder.Configuration);
        builder.Services.AddInventoryModule(builder.Configuration);

        builder.Services.AddMediatrWithAssemblies(
                productAssembly,
                basketAssembly,
                identityAssembly,
                orderAssembly,
                paymentAssembly,
                shipmentAssembly,
                inventoryAssembly
);


        builder.Services.AddMassTransit(cfg =>
        {
            cfg.AddConsumers(identityAssembly);
            cfg.AddConsumers(basketAssembly);
            cfg.AddConsumers(productAssembly);
            cfg.AddConsumers(orderAssembly);
            cfg.AddConsumers(inventoryAssembly);


            cfg.SetKebabCaseEndpointNameFormatter();
            cfg.SetInMemorySagaRepositoryProvider();


            cfg.UsingRabbitMq((context, rmq) =>
            {
                rmq.Host(builder.Configuration["RabbitMq:Host"], h =>
                {
                    h.Username(builder.Configuration["RabbitMq:UserName"]!);
                    h.Password(builder.Configuration["RabbitMq:Password"]!);
                });

                rmq.ConfigureEndpoints(context);
            });
        });

        builder.Services.AddControllers()
            .AddApplicationPart(inventoryAssembly)
            .AddApplicationPart(productAssembly)
            .AddApplicationPart(basketAssembly)
            .AddApplicationPart(identityAssembly)
            .AddApplicationPart(orderAssembly)
            .AddControllersAsServices();


        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddSwaggerGen(c =>
        {
            c.EnableAnnotations();
            c.SupportNonNullableReferenceTypes();

            c.SwaggerDoc("v1", new OpenApiInfo { Title = "API", Version = "v1" });

            // include XML comments (generated by <GenerateDocumentationFile>true</GenerateDocumentationFile>)
            var asm = Assembly.GetExecutingAssembly();
            var xmlFile = $"{asm.GetName().Name}.xml";
            var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            if (File.Exists(xmlPath))
            {
                c.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
            }

            // show controllers grouped by controller name (you already had this)
            c.TagActionsBy(api =>
            {
                var ns = api.ActionDescriptor.RouteValues["controller"];
                return new[] { ns ?? "API" };
            });

            // Add Bearer JWT security definition so you can authorize in Swagger UI
            c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                Name = "Authorization",
                In = ParameterLocation.Header,
                Type = SecuritySchemeType.Http,
                Scheme = "bearer",
                BearerFormat = "JWT"
            });

            c.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
                    },
                    Array.Empty<string>()
                }
            });
        });


        builder.Services.AddCors(options =>
        {
            options.AddPolicy("allow", policy =>
            {
                policy.WithOrigins("http://localhost:3000")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials();
            });
        });

        builder.Services.AddHttpClient("GeoIpClient", client =>
        {
            client.BaseAddress = new Uri("https://ipapi.co");
            client.Timeout = TimeSpan.FromSeconds(5);
            client.DefaultRequestHeaders.Add("Accept", "application/json");
        });


        var app = builder.Build();

        if (app.Environment.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        // ensure Swagger middleware is before routing/auth if you want to allow anonymous access to the UI
        app.UseSwagger();
        app.UseSwaggerUI(c =>
        {
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1");
            c.DocumentTitle = "API Docs";
            // To serve Swagger UI at app root set RoutePrefix = string.Empty
            // c.RoutePrefix = string.Empty;
        });
        // how to add cors policy

        app.UseCors("allow");

        app.UseIdentityModule();
        app.UseProductModule();
        app.UseBasketModule();
        app.UseOrderModule();
        app.UseShipmentModule();
        app.UsePaymentModule();
        app.UseInventoryModule();
        app.UseAuthentication();
        app.UseAuthorization();


        app.MapControllers();



        app.Use(async (ctx, next) =>
        {
            Console.WriteLine($"[AUTH] IsAuthenticated: {ctx.User?.Identity?.IsAuthenticated}");
            Console.WriteLine($"[AUTH] Claims: {string.Join(", ", ctx.User?.Claims.Select(c => $"{c.Type}={c.Value}") ?? [])}");
            await next();
        });
        app.UseSerilogRequestLogging();

        app.Run();
    }
}
